// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"
	models "src/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockAlbumRepository is a mock of AlbumRepository interface.
type MockAlbumRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAlbumRepositoryMockRecorder
}

// MockAlbumRepositoryMockRecorder is the mock recorder for MockAlbumRepository.
type MockAlbumRepositoryMockRecorder struct {
	mock *MockAlbumRepository
}

// NewMockAlbumRepository creates a new mock instance.
func NewMockAlbumRepository(ctrl *gomock.Controller) *MockAlbumRepository {
	mock := &MockAlbumRepository{ctrl: ctrl}
	mock.recorder = &MockAlbumRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlbumRepository) EXPECT() *MockAlbumRepositoryMockRecorder {
	return m.recorder
}

// AddAlbum mocks base method.
func (m *MockAlbumRepository) AddAlbum(album *models.Album) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAlbum", album)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAlbum indicates an expected call of AddAlbum.
func (mr *MockAlbumRepositoryMockRecorder) AddAlbum(album interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAlbum", reflect.TypeOf((*MockAlbumRepository)(nil).AddAlbum), album)
}

// AddTrackToAlbum mocks base method.
func (m *MockAlbumRepository) AddTrackToAlbum(albumId uint64, track *models.Track) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTrackToAlbum", albumId, track)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTrackToAlbum indicates an expected call of AddTrackToAlbum.
func (mr *MockAlbumRepositoryMockRecorder) AddTrackToAlbum(albumId, track interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTrackToAlbum", reflect.TypeOf((*MockAlbumRepository)(nil).AddTrackToAlbum), albumId, track)
}

// DeleteAlbum mocks base method.
func (m *MockAlbumRepository) DeleteAlbum(id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAlbum", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAlbum indicates an expected call of DeleteAlbum.
func (mr *MockAlbumRepositoryMockRecorder) DeleteAlbum(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAlbum", reflect.TypeOf((*MockAlbumRepository)(nil).DeleteAlbum), id)
}

// DeleteTrackFromAlbum mocks base method.
func (m *MockAlbumRepository) DeleteTrackFromAlbum(albumId, trackId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrackFromAlbum", albumId, trackId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTrackFromAlbum indicates an expected call of DeleteTrackFromAlbum.
func (mr *MockAlbumRepositoryMockRecorder) DeleteTrackFromAlbum(albumId, trackId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrackFromAlbum", reflect.TypeOf((*MockAlbumRepository)(nil).DeleteTrackFromAlbum), albumId, trackId)
}

// GetAlbum mocks base method.
func (m *MockAlbumRepository) GetAlbum(id uint64) (*models.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbum", id)
	ret0, _ := ret[0].(*models.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbum indicates an expected call of GetAlbum.
func (mr *MockAlbumRepositoryMockRecorder) GetAlbum(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbum", reflect.TypeOf((*MockAlbumRepository)(nil).GetAlbum), id)
}

// GetAllTracksForAlbum mocks base method.
func (m *MockAlbumRepository) GetAllTracksForAlbum(albumId uint64) ([]*models.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTracksForAlbum", albumId)
	ret0, _ := ret[0].([]*models.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTracksForAlbum indicates an expected call of GetAllTracksForAlbum.
func (mr *MockAlbumRepositoryMockRecorder) GetAllTracksForAlbum(albumId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTracksForAlbum", reflect.TypeOf((*MockAlbumRepository)(nil).GetAllTracksForAlbum), albumId)
}

// UpdateAlbum mocks base method.
func (m *MockAlbumRepository) UpdateAlbum(album *models.Album) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAlbum", album)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAlbum indicates an expected call of UpdateAlbum.
func (mr *MockAlbumRepositoryMockRecorder) UpdateAlbum(album interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAlbum", reflect.TypeOf((*MockAlbumRepository)(nil).UpdateAlbum), album)
}
