// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"
	models "src/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockTrackRepository is a mock of TrackRepository interface.
type MockTrackRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrackRepositoryMockRecorder
}

// MockTrackRepositoryMockRecorder is the mock recorder for MockTrackRepository.
type MockTrackRepositoryMockRecorder struct {
	mock *MockTrackRepository
}

// NewMockTrackRepository creates a new mock instance.
func NewMockTrackRepository(ctrl *gomock.Controller) *MockTrackRepository {
	mock := &MockTrackRepository{ctrl: ctrl}
	mock.recorder = &MockTrackRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackRepository) EXPECT() *MockTrackRepositoryMockRecorder {
	return m.recorder
}

// DeleteTrack mocks base method.
func (m *MockTrackRepository) DeleteTrack(trackId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrack", trackId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTrack indicates an expected call of DeleteTrack.
func (mr *MockTrackRepositoryMockRecorder) DeleteTrack(trackId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrack", reflect.TypeOf((*MockTrackRepository)(nil).DeleteTrack), trackId)
}

// GetTrack mocks base method.
func (m *MockTrackRepository) GetTrack(id uint64) (*models.TrackMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrack", id)
	ret0, _ := ret[0].(*models.TrackMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrack indicates an expected call of GetTrack.
func (mr *MockTrackRepositoryMockRecorder) GetTrack(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrack", reflect.TypeOf((*MockTrackRepository)(nil).GetTrack), id)
}

// GetTracksByPartName mocks base method.
func (m *MockTrackRepository) GetTracksByPartName(name string, offset, limit int) ([]*models.TrackMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracksByPartName", name, offset, limit)
	ret0, _ := ret[0].([]*models.TrackMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByPartName indicates an expected call of GetTracksByPartName.
func (mr *MockTrackRepositoryMockRecorder) GetTracksByPartName(name, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByPartName", reflect.TypeOf((*MockTrackRepository)(nil).GetTracksByPartName), name, offset, limit)
}

// UpdateTrack mocks base method.
func (m *MockTrackRepository) UpdateTrack(track *models.TrackMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrack", track)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrack indicates an expected call of UpdateTrack.
func (mr *MockTrackRepositoryMockRecorder) UpdateTrack(track interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrack", reflect.TypeOf((*MockTrackRepository)(nil).UpdateTrack), track)
}
