CREATE TYPE ALBUM_TYPE AS ENUM ('single', 'LP', 'EP');

CREATE TABLE IF NOT EXISTS albums (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    cover VARCHAR(254) NOT NULL UNIQUE,
    type ALBUM_TYPE NOT NULL
);

CREATE TABLE IF NOT EXISTS genres(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS authors(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL
);

CREATE TABLE IF NOT EXISTS tracks(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source VARCHAR(254) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    genre INT REFERENCES genres(id)
);

CREATE TABLE IF NOT EXISTS tracks_authors(
    producer_id INT NOT NULL REFERENCES authors(id),
    track_id INT NOT NULL REFERENCES tracks(id),
    PRIMARY KEY (producer_id, track_id)
);

CREATE TABLE IF NOT EXISTS albums_tracks(
    album_id INT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
    track_id INT NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
    PRIMARY KEY (album_id, track_id)
);
