CREATE TABLE IF NOT EXISTS outbox(
    id SERIAL PRIMARY KEY,
    event_id TEXT NOT NULL,
    track_id INTEGER NOT NULL,
    source VARCHAR(254) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    genre INT REFERENCES genres(id),
    type VARCHAR(100) NOT NULL,
    sent BOOLEAN DEFAULT FALSE
);
